name = "Server Mods"
author = "Michael Pennington"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcd6ef1fa2f072d38922fe3e869add7d0d0591f449a58b7c1e50c70a41679b8a"

[versions]
fabric = "0.19.2"
minecraft = "26.1"

[options]
