name = "Server Mods"
author = "Michael Pennington"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd977e51cecedf13df7c28e2b95ef93b7ca69f0d79adcc824471af0bcff7681c"

[versions]
fabric = "0.19.2"
minecraft = "26.1"

[options]
