name = "Server Mods"
author = "Michael Pennington"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c039b1acf6f73633acb99e9eb2f73f3c8781fbbe0ee55210548132214d59a39"

[versions]
fabric = "0.19.2"
minecraft = "26.1"

[options]
